version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:9000"  # เปิด port ให้เข้าผ่านเครื่องจริง
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
